apiVersion: v1
kind: Service
metadata:
  name: poc-events-message
  labels:
    app: poc-events-message
spec:
  type: ClusterIP
  selector:
    app: poc-events-message
  ports:
    - name: http
      port: 80
      targetPort: 3000
